version: '3'

services:
  julia_env:
    image: ijulia_dev
    command: "bash -c 'SHELL=/bin/bash jupyter lab --no-browser --ip=* --port=9000 --allow-root --notebook-dir=/home --NotebookApp.token=\"\"'"
    volumes:
      - ./:/home
      - /var/run/docker.sock:/var/run/docker.sock 
    ports:
      - 9000:9000
